# GRPC Server.
grpc:
  address: "192.168.110.30:8199"
  name:    "GoFrame-Polaris-Demo"
  logPath: "./manifest/logs/server"
  logStdout: true
  errorStack: true
  errorLogEnabled: true
  errorLogPattern: "error-{Ymd}.log"
  accessLogEnabled: true
  accessLogPattern: "access-{Ymd}.log"

# Global logging.
logger:
  path: "./manifest/logs/default"
  level: "all"
  stdout: false

# Database.
database:
  logger:
    path: "./manifest/logs/sql"
    level: "all"
    stdout: false

  default:
    link: "mysql:root:root@tcp(127.0.0.1:3306)/test"
    debug: true



